_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  BACKBONE:
    NAME: 'build_lgsnet_fpn_backbone'
  RESNETS:
    DEPTH: 50
  LGSNET:
    IN_FEATURES: ['res2', 'res3', 'res4', 'res5']
    OUT_FEATURES: ['res2', 'res3', 'res4', 'res5']
    K: 7
  ROI_HEADS:
    SCORE_THRESH_TEST: 0.
    BATCH_SIZE_PER_IMAGE: 256
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_TYPE: 'ROIAlign'
    POOLER_SAMPLING_RATIO: 2
SOLVER:
  IMS_PER_BATCH: 16
  USE_GRAD_ACC: True
  IMS_PER_GPU: 2
  BASE_LR: 0.02
  BASE_LR_LGS: 0.02
  CHECKPOINT_PERIOD: 10000
  STEPS: (60000, 80000)
  MAX_ITER: 90000
INPUT:
  MIN_SIZE_TRAIN: (800, )
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
OUTPUT_DIR: './faster_rcnn_R_50_LGS_FPN_12e'
