_BASE_: '../Base-RCNN-FPN.yaml'
MODEL:
  WEIGHTS: 'detectron2://ImageNetPretrained/MSRA/R-50.pkl'
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    SCORE_THRESH_TEST: 0.
    BATCH_SIZE_PER_IMAGE: 256
  ROI_BOX_HEAD:
    POOLER_TYPE: 'ROIAlign'
    POOLER_SAMPLING_RATIO: 2
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
  CHECKPOINT_PERIOD: 10000
  STEPS: (60000, 80000)
  MAX_ITER: 90000
INPUT:
  MIN_SIZE_TRAIN: (800, )
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
OUTPUT_DIR: 'faster_rcnn_R_50_FPN_6e'
