_BASE_: "../Base-RetinaNet.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  BACKBONE:
    NAME: 'build_retinanet_lgsnet_fpn_backbone'
  RESNETS:
    DEPTH: 101
    OUT_FEATURES: ['res2', 'res3', 'res4', 'res5']
  LGSNET:
    IN_FEATURES: ['res2', 'res3', 'res4', 'res5']
    OUT_FEATURES: ['res3', 'res4', 'res5']
    K: 7
  FPN:
    IN_FEATURES: ['res3', 'res4', 'res5']
  RETINANET:
    SMOOTH_L1_LOSS_BETA: 0.0
    SCORE_THRESH_TEST: 0.
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  BASE_LR_LGS: 0.02
  USE_GRAD_ACC: True
  IMS_PER_GPU: 2
  CHECKPOINT_PERIOD: 10000
  STEPS: (60000, 80000)
  MAX_ITER: 90000
INPUT:
  MIN_SIZE_TRAIN: (800, )
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
OUTPUT_DIR: './retinanet_R_101_LGS_FPN_12e'
