_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  MASK_ON: True
  WEIGHTS: "detectron2://ImageNetPretrained/FAIR/X-101-32x8d.pkl"
  PIXEL_STD: [57.375, 57.120, 58.395]
  BACKBONE:
    NAME: 'build_lgsnet_fpn_backbone'
  RESNETS:
    STRIDE_IN_1X1: False  # this is a C2 model
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
    DEPTH: 101
  LGSNET:
    IN_FEATURES: ['res2', 'res3', 'res4', 'res5']
    OUT_FEATURES: ['res2', 'res3', 'res4', 'res5']
    K: 7
  ROI_HEADS:
    SCORE_THRESH_TEST: 0.
    BATCH_SIZE_PER_IMAGE: 256
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_TYPE: 'ROIAlign'
    POOLER_SAMPLING_RATIO: 2
  ROI_MASK_HEAD:
    POOLER_RESOLUTION: 14
    POOLER_TYPE: 'ROIAlign'
    POOLER_SAMPLING_RATIO: 2 
#DATASETS:
#  TEST: ("coco_2017_test-dev",)
SOLVER:
  IMS_PER_BATCH: 16
  USE_GRAD_ACC: True
  IMS_PER_GPU: 2
  BASE_LR: 0.02
  BASE_LR_LGS: 0.02
  CHECKPOINT_PERIOD: 10000
  STEPS: (210000, 250000)
  MAX_ITER: 270000
INPUT:
  MIN_SIZE_TRAIN: (600, 700, 800, 900, 1000)
  MAX_SIZE_TRAIN: 1666
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
OUTPUT_DIR: './mask_rcnn_X_101_32x8d_LGS_FPN_36e_ms'
