_BASE_: '../Base-RCNN-FPN.yaml'
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  BACKBONE:
    NAME: 'build_lgsnet_fpn_backbone'
  RESNETS:
    DEPTH: 101
  LGSNET:
    IN_FEATURES: ['res2', 'res3', 'res4', 'res5']
    OUT_FEATURES: ['res2', 'res3', 'res4', 'res5']
    K: 7
  ROI_HEADS:
    NUM_CLASSES: 20
    SCORE_THRESH_TEST: 0.
    BATCH_SIZE_PER_IMAGE: 256
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_TYPE: 'ROIAlign'
    POOLER_SAMPLING_RATIO: 2
DATASETS:
  TRAIN: ('voc_2007_trainval', 'voc_2012_trainval')
  TEST: ('voc_2007_test',)
SOLVER:
  IMS_PER_BATCH: 16
  USE_GRAD_ACC: True
  IMS_PER_GPU: 2
  BASE_LR: 0.02
  BASE_LR_LGS: 0.02
  CHECKPOINT_PERIOD: 1000
  STEPS: (21000, 26000)
  MAX_ITER: 27000
  WARMUP_ITERS: 300
INPUT:
  MIN_SIZE_TRAIN: (600, 700, 800, 900, 1000)
  MAX_SIZE_TRAIN: 1666
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
TEST:
  AUG:
    ENABLED: False
    MIN_SIZES:  (400, 500, 600, 700, 800, 900, 1000, 1100, 1200)
    MAX_SIZE:  2000
    FLIP: True
  DETECTIONS_PER_IMAGE: 300
OUTPUT_DIR: './faster_rcnn_R_101_LGS_FPN_voc07_ms'
